title: Using the list function in Python
hero_image: images/banner.png
description: list-function description
version: 4
listed: false
copyedit: false
last_tested: "2021-10-27"
steps:
  - 
    title: Using the list function in Python
